services:
  mysql:
    image: mysql:8.0
    container_name: loftbarber_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loftbarber
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - loftbarber_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: loftbarber_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: loftbarber
      DB_USER: user
      DB_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRE: 7d
      BCRYPT_ROUNDS: 12
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - loftbarber_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: loftbarber_frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:3001/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - loftbarber_network

volumes:
  mysql_data:

networks:
  loftbarber_network:
    driver: bridge
