# DIAGNOSTIC COMPLET - PROBLÈME 404 API
echo '========================================'
echo '🔍 DIAGNOSTIC COMPLET LOFTBARBER API 404'
echo '========================================'

echo ''
echo '1️⃣ VÉRIFICATION CPANEL NODE.JS :'
echo '   📍 Allez dans cPanel > Node.js Selector > Applications'
echo '   ✅ Loftbarber doit être listé'
echo '   ✅ Status doit être \"Running\" (vert)'
echo '   ✅ Application URL: /'
echo '   ✅ Startup file: server.js'
echo ''
echo '   Si pas listé ou arrêté :'
echo '   - Cliquez \"Setup Node.js App\"'
echo '   - Root: /home/dije1636/public_html/loftbarber'
echo '   - URL: /'
echo '   - File: server.js'
echo '   - Log: /home/dije1636/logs/loftbarber.log'

echo ''
echo '2️⃣ VARIABLES D\'ENVIRONNEMENT (CRITIQUE) :'
echo '   Dans cPanel > Node.js > Applications > loftbarber > Environment variables'
echo '   Ajoutez ces variables EXACTEMENT :'
echo ''
echo '   NODE_ENV=production'
echo '   PASSENGER_APP_ENV=production'
echo '   DB_HOST=localhost'
echo '   DB_USER=dije1636_loftbarber'
echo '   DB_PASSWORD=[VOTRE_MOT_DE_PASSE_RÉEL]'
echo '   DB_NAME=dije1636_loftbarber'
echo '   JWT_SECRET=[VOTRE_SECRET_JWT]'
echo ''
echo '   ⚠️ REMPLACEZ LES VALEURS PAR LES VÔTRES !'

echo ''
echo '3️⃣ INSTALLATION DÉPENDANCES :'
echo '   Dans cPanel > Node.js > Applications > loftbarber > Run NPM Install'
echo '   Ou manuellement :'
echo '   cd ~/public_html/loftbarber && npm install'

echo ''
echo '4️⃣ REDÉMARRAGE APPLICATION :'
echo '   Dans cPanel > Node.js > Applications > Restart'

echo ''
echo '5️⃣ VÉRIFICATION LOGS :'
echo '   tail -20 ~/logs/loftbarber.log'

echo ''
echo '6️⃣ TEST FINAL :'
echo '   curl -I https://loftbarber.com/api/v1/health'
echo '   Doit retourner 200 OK (pas 404)'

echo ''
echo '========================================'
echo '📞 SI ÇA NE MARCHE PAS :'
echo '1. Vérifiez que la DB MySQL existe dans cPanel > MySQL Databases'
echo '2. Vérifiez que l\'utilisateur dije1636_loftbarber a accès à la DB'
echo '3. Vérifiez que le domaine loftbarber.com pointe vers o2switch'
echo '========================================'
