#!/bin/bash
echo "🔧 CORRECTIONS POUR O2SWITCH - PROBLÈMES IDENTIFIÉS"
echo "=================================================="

echo ""
echo "❌ PROBLÈMES TROUVÉS:"
echo "1. Node.js et npm non disponibles dans le terminal cPanel"
echo "2. Passenger non configuré correctement"
echo "3. Application Node.js pas démarrée"
echo "4. API retourne 404 (pas de serveur backend actif)"
echo ""

echo "✅ SOLUTIONS À APPLIQUER:"
echo ""

echo "1. CONFIGURER NODE.JS DANS CPANEL:"
echo "   - Aller dans cPanel > Node.js Selector"
echo "   - Sélectionner votre domaine"
echo "   - Choisir Node.js version 18+"
echo "   - Application root: ~/public_html/loftbarber"
echo "   - Application URL: /"
echo "   - Application startup file: server.js"
echo "   - Passenger log file: ~/logs/loftbarber.log"
echo ""

echo "2. VARIABLES D'ENVIRONNEMENT À AJOUTER:"
echo "   NODE_ENV=production"
echo "   PASSENGER_APP_ENV=production"
echo "   DB_HOST=localhost"
echo "   DB_USER=[votre_user_db]"
echo "   DB_PASSWORD=[votre_password_db]"
echo "   DB_NAME=[votre_nom_db]"
echo "   JWT_SECRET=[votre_secret_jwt_secure]"
echo ""

echo "3. CRÉER LA BASE DE DONNÉES:"
echo "   - Aller dans cPanel > MySQL Databases"
echo "   - Créer une base de données"
echo "   - Créer un utilisateur MySQL"
echo "   - Donner tous les privilèges à l'utilisateur sur la DB"
echo ""

echo "4. REDÉMARRER L'APPLICATION:"
echo "   - Dans cPanel > Node.js Selector > Applications"
echo "   - Cliquer sur 'Restart' pour LoftBarber"
echo ""

echo "5. VÉRIFIER LES LOGS:"
echo "   - Consulter ~/logs/loftbarber.log"
echo "   - Vérifier les erreurs de démarrage"
echo ""

echo "6. TEST FINAL:"
echo "   - Visiter https://votre-domaine.com/"
echo "   - Tester le login avec admin@loftbarber.com / admin123"
echo ""

echo "=================================================="
echo "📞 SI PROBLÈMES PERSISTANTS:"
echo "   - Contacter le support o2switch"
echo "   - Fournir les logs d'erreur"
echo "   - Vérifier la configuration Passenger"
echo "=================================================="
